### ISSUE TITLE
Options, radio button issue in Chrome 57+

### ISSUE THREAD

**Issue by chris-oreilly** [AjaxGb/Better-Chrome-Native-Video#11]
The firstClick option isn't being set or restored correctly in recent versions of Chrome.

The type of `HTMLFieldSetElement.elements` changed so that `elements["firstClick"]` simply returns the first radio button named `firstClick`, regardless of which option is selected. `HTMLFormElement.elements` is still the correct type, so `elements["firstClick"]` is a `RadioNodeList` with the selected button's value.

Reference: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement#Browser_compatibility)

**Comment by AjaxGb** [comment]
Thanks for the heads up.
