### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kostuj** [AjaxGb/Better-Chrome-Native-Video#12]
I am working with a great guy where one of our only remaining and extremely frustrating issues is not being able to get some frame-by-frame playback control in Chrome for a sports-related web analysis application.  He has what is needed working well in Firefox and Edge browsers, but even with this extension enabled in Chrome (apparently the most widely used browser by a wide margin) there is really no keyboard control and no frame-by-frame playback available.  I am not sure what details might be needed from me for any possible diagnosis, but any suggestions would be appreciated.  Thank you.

**Comment by AjaxGb** [comment]
Is the video you're watching using the native HTML5 video player (see the image on the Chrome Store listing), or a custom one like YouTube or Vimeo? This extension does not support custom players, since A) they usually provide their own shortcuts, and B) the extension would probably conflict with the player unless specific work was put in to make the two compatible. If you could provide a link to the non-responsive video, I could be of more help.

Also, what sort of application are you referring to? How is it interfacing with the browser and this extension?

**Comment by kostuj** [comment]
Hi Sol,

 

Thank you for your extremely quick and kind reply.  I really appreciate it.
I was right in the middle of writing my developer again about whether he is
using a dedicated custom video player in the application or simply the ones
native to each browser, because he did not specifically answer that for me
before.  I will have to follow up about that.

 

The (golf-club-fitting-related) application uses the R language and
something called Shiny and we are testing it first locally on my computer,
so presently I am not even sure how I can link you to what we have been
specifically experiencing.  I will follow up further when I get a little
more information.  Thank you very much again.

 

  _____

**Comment by kostuj** [comment]
I apologize for an update delay, but it took a little time to get some additional information from my contractor.  His comments are as follows:

"The application is called a Shiny application. It is written in the R  programming language but generates HTML and allows for Javascript functionality.  The video player is a native HTML5 video player.

The app also has extra  buttons to change the currentTime element of the video through Javascript  functions, it may work similarly to the extension. The functionality of the  buttons work in Firefox and Edge browsers.

Please see the screenshots  for the HTML5 video code and Javascript functionality."
![screenshot](https://user-images.githubusercontent.com/31488628/30168947-8820c816-93b0-11e7-9937-b7bd4d40536f.png)

I personally do not understand the technicalities or whether any of this might be helpful, but thank you very much in advance for any comments.  I really appreciate it.  I will try to determine how to develop and post a link to the problem part of the application in case that might be helpful.  Thank you very much again.

**Comment by AjaxGb** [comment]
Did you intentionally close this report? I can't see anything wrong with the code you posted, but I have no experience with either Shiny or R, so that doesn't count for too much. Without an actual website to debug, I'm afraid that I can only be of limited help.

**Comment by kostuj** [comment]
Hi Sol,

 

Thank you very much for your note.

 

I did not intentionally want to close the report and apparently did so
inadvertently.  If you have the authority to reopen it I ask you to please
do so.

 

Thank you also for your comments regarding the code.  Maybe someone else
will chime in, and in the meantime I will try to learn how to get the
application actually online to be inspected.

 

Thank you again.  I really appreciate it.

 

Sincerely,

Bill

 

  _____

**Comment by kostuj** [comment]
Much obliged.  I appreciate your help.  Thank you very much again.

 

Sincerely,

Bill

 

  _____

**Comment by AjaxGb** [comment]
Since it's been most of a year with no updates, I'm closing this issue. Let me know if anything changes.
