### ISSUE TITLE
Doesn't work with local videos

### ISSUE THREAD

**Issue by veyndan** [AjaxGb/Better-Chrome-Native-Video#13]
# Issue recreation

* Download an `mkv` file to computer.
* Drag the `mkv` file on to a Chrome window

# Expectation vs Outcome

I expected to be able to use the controls provided by this extension this way, but it doesn't work. I checked to see if the extension works on non local video files ([this one](https://www.w3schools.com/html/mov_bbb.mp4)), and it indeed works.

Chrome version: 60.0.3112.113
HTML5 Video Keyboard Shortcuts version: 4.1.3

Thanks for the awesome extension!

**Comment by AjaxGb** [comment]
All Chrome extensions are blocked from accessing local files by default. To change this you can go to chrome://extensions/ and check the "Allow access to file URLs" checkbox under this extension.

**Comment by veyndan** [comment]
Awesome, thanks! I had no idea about this security precaution in Chrome.
