### ISSUE TITLE
[Feature Request] Buttons?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [AjaxGb/Better-Chrome-Native-Video#15]
Awesome extension. I'm really glad I stumbled across it. Click to play/pause and double-click fullscreen should be the default behavior, so it's great that you've made that a reality.

Chrome's native html5 player sacrifices precision for performance when seeking in the timeline. It ignores spaces too close between keyframes, so trying to skip 10-20 seconds usually doesn't register, and depending on the encode/length of the vid, that margin for error can be much greater, making it hard to seek within minutes of accuracy. 

Your shortcuts are great for circumventing this accuracy issue, but to me, they would be far more accessible if they were available as skip buttons. Ideally, they could be integrated directly into `::-webkit-media-controls`, otherwise, a hover overlay would suffice.

The 3 configurable increments in either direction are really useful, so a clickable element for all 6 would be justifiable. Perhaps buttons with 1, 2, & 3 chevrons in either direction?

**Comment by Lewiscowles1986** [comment]
Would this and #14 not be related I wonder?

Because the goals are accessible, any buttons added would need a mechanism to continue that theme.

I'm not 100% sure how it should work, but please see my comments on #14

**Comment by narcolepticinsomniac** [comment]
Who knows? Just a title with no description provided. I'd guess he wants to be able to assign shortcuts to different hotkeys though, so not really the same thing.

It's been 4 months without a response from the dev on either issue, so I'm not holding my breath.

**Comment by Lewiscowles1986** [comment]
Not the same, but complimentary was my thinking. No point having new buttons if they are not made accessible as that seems to be a large part of what this project is for.

**Comment by narcolepticinsomniac** [comment]
@Lewiscowles1986 I eventually incorporated all the shortcuts into [a custom native player script](https://greasyfork.org/en/scripts/404717-custom-native-html5-player-with-shortcuts).
