### ISSUE TITLE
needs update

### ISSUE THREAD

**Issue by garywzh** [AjaxGb/Better-Chrome-Native-Video#16]
with new chrome html5 video player released, I think this tool maybe need to be updated

**Comment by AjaxGb** [comment]
Still works fine as far as I can tell. If you have a specific bug report, please open a more descriptive issue for it.

**Comment by garywzh** [comment]
I am using the latest Chrome Version 67.0.3396.99, and it is not working.

**Comment by AjaxGb** [comment]
As I said, please be more specific. Which site are you using it on?

**Comment by garywzh** [comment]
ok, I checked some other websites, it is working as expected.
I am using this extension 
https://chrome.google.com/webstore/detail/openload-video-only/leallakffbiflfgpmamdgcojddnbfdgo
it redirect openload video player to vanila chrome html5 video player, and when this happens, the shortcuts are not working as expected.
anyway, thank you
