### ISSUE TITLE
Issue with direct URL

### ISSUE THREAD

**Issue by sajjadalis** [AjaxGb/Better-Chrome-Native-Video#18]
Hello,

First of all, thanks for this add-on. It works fine when i watch html5 video on some site but when i play video with a direct URL like http://examples.com/file.mp4 then it doesn't work at all. Any solution for this please?

**Comment by AjaxGb** [comment]
Direct URLs are working fine for me. Would this happen to be a file URL (`file:///`)? Because by default extensions can't access those. You'd need to go to chrome://extensions and turn on "Allow access to file URLs".

**Comment by bmomani1** [comment]
thank you guys that was my issue, I opened a local file and shortcut did not work
I turned on 

> "Allow access to file URLs".

and it worked
