### ISSUE TITLE
Keyboard focus on HTML5 video player snatched by GUI buttons - can this extension prevent it?

### ISSUE THREAD

**Issue by valenhas** [AjaxGb/Better-Chrome-Native-Video#21]
If one clicks on any of the HTML5 player controls of recent Chromium, the keyboard focus is snatched, so that spacebar and left and right do not perform their main functions play/pause and skipping anymore. For example, clicking on the fullscreen button will cause spacebar to toggle fullscreen, instead of stopping the video like it did before the click.

Since it's probably hopeless to get Chromium core developers to change this - I suspect some accessibility guidelines - could this extension prevent that keyboard snatching, so that at least spacebar and left right arrow keys work as expected? It seems to be quite close to these parts of the API, I even hoped it would fix this.

**Comment by AjaxGb** [comment]
Thanks for the heads up! I don't use Chrome much anymore, so that was helpful. I'm pushing out a new 4.1.5 version that fixes this, so you should see that soon.

**Comment by valenhas** [comment]
Works on the native player, thank you!
